Repository chanzuckerberg/napari-hub, pull requests merged in 2023-03, with the labels that each got.

#816 Adding behavioural tests for API
  .github/workflows/backend-bdd-tests.yml
  .github/workflows/backend-tests.yml
  .github/workflows/deploy.yml
  .github/workflows/push-rdev.yml
  backend/bdd_tests/__init__.py
  backend/bdd_tests/conftest.py
  backend/bdd_tests/pytest.ini
  backend/bdd_tests/scenarios/category.feature
  backend/bdd_tests/scenarios/metric.feature
  backend/bdd_tests/scenarios/plugin.feature
  backend/bdd_tests/test_category.py
  backend/bdd_tests/test_metric.py
  backend/bdd_tests/test_plugin.py
  backend/bdd_tests/test_utils.py
  backend/test-requirements.txt
Labels: new-feature

#917 Adding data workflows ETL infrastructure
  .happy/terraform/modules/ecs-stack/main.tf
  data-workflows/Dockerfile
  data-workflows/__init__.py
  data-workflows/handler.py
  data-workflows/requirements.txt
  docker-compose.yml
Labels: new-feature, infrastructure

#941 Do not add `blocked` plugins to `public-plugins.json`
  backend/api/model.py
Labels: bug-fix

#945 Renaming collections module
  backend/api/app.py
  backend/api/plugin_collections.py
Labels: bug-fix

#926 ETL workflow for install activity
  .happy/terraform/modules/dynamo/main.tf
  .happy/terraform/modules/dynamo/variables.tf
  data-workflows/activity/__init__.py
  data-workflows/activity/install_activity_model.py
  data-workflows/activity/processor.py
  data-workflows/activity/snowflake_adapter.py
  data-workflows/activity/tests/__init__.py
  data-workflows/activity/tests/test_install_activity_model.py
  data-workflows/activity/tests/test_processor.py
  data-workflows/activity/tests/test_snowflake_adapter.py
  data-workflows/conftest.py
  data-workflows/handler.py
  data-workflows/requirements.txt
  data-workflows/test-requirements.txt
  data-workflows/tests/__init__.py
  data-workflows/tests/test_handler.py
  data-workflows/utils/__init__.py
  data-workflows/utils/tests/__init__.py
  data-workflows/utils/tests/test_utils.py
  data-workflows/utils/utils.py
Labels: new-feature

#957 Behavioural test github workflow update
  .github/workflows/backend-bdd-tests.yml
  .github/workflows/deploy.yml
  .github/workflows/push-rdev.yml
  backend/bdd_tests/scenarios/metric.feature
  backend/bdd_tests/test_metric.py
  backend/test-requirements.txt
Labels: improvement

#935 Updating metric API to use dynamoDB
  .happy/terraform/modules/ecs-stack/main.tf
  backend/api/_tests/test_activity_dashboard.py
  backend/api/_tests/test_fixtures.py
  backend/api/app.py
  backend/api/model.py
  backend/api/models/__init__.py
  backend/api/models/_tests/__init__.py
  backend/api/models/_tests/test_metrics.py
  backend/api/models/metrics.py
  backend/bdd_tests/scenarios/metric.feature
  backend/bdd_tests/test_metric.py
  backend/requirements.txt
  data-workflows/activity/tests/test_snowflake_adapter.py
Labels: improvement

#971 Setting up local dynamo
  backend/api/models/metrics.py
  data-workflows/activity/install_activity_model.py
  data-workflows/local-dynamo-setup.sh
Labels: improvement
