Repository chanzuckerberg/napari-hub, pull requests merged in 2023-09, with the labels that each got.

#1244 Updating BDD tests for 404
  backend/bdd_tests/scenarios/plugin.feature
Labels: bug-fix

#1218 Refactoring to use nhcommons in plugins module
  .github/workflows/plugins-tests.yml
  .happy/terraform/modules/ecs-stack/main.tf
  docker-compose.yml
  plugins/Dockerfile
  plugins/_tests/test_discovery.py
  plugins/conftest.py
  plugins/get_plugin_manifest.py
  plugins/models/_tests/__init__.py
  plugins/models/_tests/test_plugin.py
  plugins/models/plugin_metadata.py
  plugins/models/pluginmetadata.py
  plugins/requirements.txt
  plugins/test-requirements.txt
  plugins/tests/__init__.py
  plugins/tests/conftest.py
  plugins/tests/test_discovery.py
  plugins/tests/test_models_plugin_metadata.py
  plugins/utils/__init__.py
  plugins/utils/s3_adapter.py
Labels: maintenance

#1245 Removing Collection frontend components
  frontend/i18n/en/collections.json
  frontend/i18n/en/common.json
  frontend/i18n/en/pageTitles.json
  frontend/mock-server.js
  frontend/src/components/AppBar/__snapshots__/AppBar.test.tsx.snap
  frontend/src/components/AppBar/useAppBarLinks.ts
  frontend/src/components/CollectionPage/CollectionCoverImage.tsx
  frontend/src/components/CollectionPage/CollectionInfo.tsx
  frontend/src/components/CollectionPage/CollectionLinks.tsx
  frontend/src/components/CollectionPage/CollectionPage.tsx
  frontend/src/components/CollectionPage/CollectionPluginList.tsx
  frontend/src/components/CollectionPage/context.tsx
  frontend/src/components/CollectionPage/index.ts
  frontend/src/components/CollectionsPage/CollectionCard.tsx
  frontend/src/components/CollectionsPage/CollectionsPage.tsx
  frontend/src/components/CollectionsPage/context.tsx
  frontend/src/components/CollectionsPage/index.ts
  frontend/src/components/Layout/__snapshots__/Layout.test.tsx.snap
  frontend/src/components/PageMetadata/usePageMetadata.ts
  frontend/src/constants/i18n.ts
  frontend/src/fixtures/collections.json
  frontend/src/hooks/useLinks.ts
  frontend/src/pages/collections/[symbol].tsx
  frontend/src/pages/collections/index.tsx
  frontend/src/store/featureFlags.ts
  frontend/src/types/collections.ts
  frontend/src/types/index.ts
  frontend/src/utils/HubAPIClient.ts
  frontend/src/utils/sitemap.server.ts
  frontend/src/utils/validate/index.ts
  frontend/src/utils/validate/validateCollectionData.ts
  frontend/src/utils/validate/validateCollectionIndexData.ts
Labels: maintenance

#1243 Remove backend components for preview page
  .github/workflows/backend-tests.yml
  backend/api/app.py
  backend/api/model.py
  backend/api/s3.py
  backend/get_preview.py
  backend/preview/__init__.py
  backend/preview/_tests/__init__.py
  backend/preview/_tests/test_preview_meta.py
  backend/preview/preview.py
  backend/utils/_tests/__init__.py
  backend/utils/_tests/test_github.py
  backend/utils/_tests/test_pypi.py
  backend/utils/_tests/test_utils.py
  backend/utils/github.py
  backend/utils/pypi.py
  backend/utils/test_utils.py
  backend/utils/utils.py
  data-workflows/utils/tests/test_zulip.py
  napari-hub-commons/src/nhcommons/tests/utils/test_citation_helper.py
  napari-hub-commons/src/nhcommons/tests/utils/test_fixtures.py
  napari-hub-commons/src/nhcommons/tests/utils/test_github_adapter.py
  napari-hub-commons/src/nhcommons/tests/utils/test_github_client_helper.py
  napari-hub-commons/src/nhcommons/tests/utils/test_pypi_adapter.py
  napari-hub-commons/src/nhcommons/utils/adapter_helpers.py
Labels: maintenance

#1246 Removing collections backend
  backend/api/app.py
  backend/api/plugin_collections.py
  backend/utils/auth.py
  backend/utils/github.py
Labels: maintenance

#1222 Updating maintenance metrics workflow to support overwrite
  .happy/terraform/modules/ecs-stack/main.tf
  data-workflows/__init__.py
  data-workflows/activity/github_activity_model.py
  data-workflows/activity/snowflake_adapter.py
  data-workflows/activity/tests/conftest.py
  data-workflows/activity/tests/test_fixture.py
  data-workflows/activity/tests/test_github_activity_model.py
  data-workflows/activity/tests/test_github_activity_type.py
  data-workflows/activity/tests/test_github_snowflake_adapter.py
  data-workflows/activity/tests/test_snowflake_adapter.py
  data-workflows/activity/utils.py
  data-workflows/utils/utils.py
  napari-hub-commons/src/nhcommons/models/github_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_github_activity.py
Labels: new-feature

#1253 Run E2E tests on production deployments
  .github/workflows/deploy.yml
Labels: cicd

#1260 disable frontend alarm for 404s
  .happy/terraform/modules/cloudwatch-alarm/main.tf
Labels: improvement

#1259 Refactoring backend to use nhcommons
  backend/Dockerfile
  backend/api/_tests/test_home.py
  backend/api/_tests/test_metrics.py
  backend/api/_tests/test_model.py
  backend/api/_tests/test_shield.py
  backend/api/app.py
  backend/api/home.py
  backend/api/metrics.py
  backend/api/model.py
  backend/api/models/__init__.py
  backend/api/models/_tests/__init__.py
  backend/api/models/_tests/conftest.py
  backend/api/models/_tests/test_category.py
  backend/api/models/_tests/test_github_activity.py
  backend/api/models/_tests/test_install_activity.py
  backend/api/models/_tests/test_plugin.py
  backend/api/models/_tests/test_plugin_metadata.py
  backend/api/models/category.py
  backend/api/models/github_activity.py
  backend/api/models/helper.py
  backend/api/models/install_activity.py
  backend/api/models/plugin.py
  backend/api/models/plugin_metadata.py
  backend/api/shield.py
  backend/requirements.txt
  docker-compose.yml
  napari-hub-commons/src/nhcommons/models/activity_helper.py
  napari-hub-commons/src/nhcommons/models/category.py
  napari-hub-commons/src/nhcommons/models/github_activity.py
  napari-hub-commons/src/nhcommons/models/install_activity.py
  napari-hub-commons/src/nhcommons/models/plugin.py
  napari-hub-commons/src/nhcommons/models/plugin_metadata.py
  napari-hub-commons/src/nhcommons/models/plugins_blocked.py
  napari-hub-commons/src/nhcommons/models/pynamo_helper.py
  napari-hub-commons/src/nhcommons/tests/models/conftest.py
  napari-hub-commons/src/nhcommons/tests/models/test_category.py
  napari-hub-commons/src/nhcommons/tests/models/test_github_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_install_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin_metadata.py
Labels: improvement

#1267 Fixing repository data being displayed incorrectly
  frontend/src/pages/plugins/[name].tsx
Labels: bug-fix

#1269 Testing all dependent modules on making changes to nhcommons
  .github/workflows/backend-tests.yml
  .github/workflows/dataworkflow-tests.yml
  .github/workflows/plugins-tests.yml
Labels: maintenance

#1270 Set API_URL for dev environment
  frontend/src/constants/env.ts
  frontend/src/utils/HubAPIClient.ts
Labels: bug-fix

#1235 Remove `authors` and `summary` from valid `config.yml` keys
  napari-hub-commons/src/nhcommons/utils/github_adapter.py
Labels: maintenance, clean-up

#1236 Remove `project_urls` from valid `config.yml` keys
  napari-hub-commons/src/nhcommons/utils/github_adapter.py
Labels: maintenance, clean-up

#1268 Updating nhcommons formatting using black
  napari-hub-commons/setup.py
  napari-hub-commons/src/nhcommons/__init__.py
  napari-hub-commons/src/nhcommons/models/activity_helper.py
  napari-hub-commons/src/nhcommons/models/github_activity.py
  napari-hub-commons/src/nhcommons/models/install_activity.py
  napari-hub-commons/src/nhcommons/models/plugin.py
  napari-hub-commons/src/nhcommons/models/plugin_metadata.py
  napari-hub-commons/src/nhcommons/models/plugin_utils.py
  napari-hub-commons/src/nhcommons/models/pynamo_helper.py
  napari-hub-commons/src/nhcommons/tests/models/conftest.py
  napari-hub-commons/src/nhcommons/tests/models/test_category.py
  napari-hub-commons/src/nhcommons/tests/models/test_github_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_install_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin_metadata.py
  napari-hub-commons/src/nhcommons/tests/utils/test_citation_helper.py
  napari-hub-commons/src/nhcommons/tests/utils/test_github_client_helper.py
  napari-hub-commons/src/nhcommons/tests/utils/test_pypi_adapter.py
  napari-hub-commons/src/nhcommons/utils/adapter_helpers.py
  napari-hub-commons/src/nhcommons/utils/auth.py
  napari-hub-commons/src/nhcommons/utils/github_adapter.py
Labels: maintenance

#1271 Updating backend, data-workflow, plugin formatting using black
  backend/api/_tests/test_fixtures.py
  backend/api/_tests/test_home.py
  backend/api/_tests/test_metrics.py
  backend/api/_tests/test_model.py
  backend/api/_tests/test_shield.py
  backend/api/app.py
  backend/api/custom_wsgi.py
  backend/api/home.py
  backend/api/model.py
  backend/api/shield.py
  backend/bdd_tests/conftest.py
  backend/bdd_tests/test_category.py
  backend/bdd_tests/test_homepage_plugin.py
  backend/bdd_tests/test_plugin.py
  backend/category/edam.py
  backend/utils/utils.py
  data-workflows/activity/install_activity_model.py
  data-workflows/activity/processor.py
  data-workflows/activity/tests/test_install_activity_model.py
  data-workflows/activity/tests/test_processor.py
  data-workflows/categories/processor.py
  data-workflows/categories/tests/test_processor.py
  data-workflows/plugin/manifest.py
  data-workflows/plugin/metadata.py
  data-workflows/plugin/tests/conftest.py
  data-workflows/plugin/tests/test_lambda_adapter.py
  data-workflows/plugin/tests/test_manifest.py
  data-workflows/plugin/tests/test_metadata.py
  data-workflows/utils/tests/test_utils.py
  plugins/tests/conftest.py
  plugins/tests/test_discovery.py
  plugins/tests/test_models_plugin_metadata.py
Labels: maintenance

#1262 Add parsing and mapping for manifest categories to EDAM terms
  data-workflows/plugin/aggregator.py
  data-workflows/plugin/categories.py
  data-workflows/plugin/manifest.py
  data-workflows/plugin/metadata.py
  data-workflows/plugin/tests/test_categories.py
  data-workflows/plugin/tests/test_manifest.py
  data-workflows/plugin/tests/test_metadata.py
Labels: new-feature

#1261 Read visibility from manifest, not github
  data-workflows/plugin/manifest.py
  data-workflows/plugin/tests/test_aggregator.py
  data-workflows/plugin/tests/test_manifest.py
  napari-hub-commons/src/nhcommons/models/plugin_utils.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin.py
  napari-hub-commons/src/nhcommons/utils/github_adapter.py
Labels: maintenance, clean-up

#1274 Remove zulip credentials from data-workflows terraform config
  .happy/terraform/modules/ecs-stack/main.tf
Labels: bug-fix

#1273 Logging pypi plugin count by page
  napari-hub-commons/src/nhcommons/tests/utils/test_pypi_adapter.py
  napari-hub-commons/src/nhcommons/utils/pypi_adapter.py
Labels: bug-fix

#1272 Adding linting check to python code
  .git-blame-ignore-revs
  .github/workflows/backend-tests.yml
  .github/workflows/dataworkflow-tests.yml
  .github/workflows/nh-commons-tests.yml
  .github/workflows/plugins-tests.yml
Labels: maintenance
