Repository chanzuckerberg/napari-hub, pull requests merged in 2023-04, with the labels that each got.

#901 E2E tests for plugin search
  .github/workflows/e2e-tests.yml
  frontend/e2e/setup/local.config.ts
  frontend/e2e/tests/home/filter.spec.ts
  frontend/e2e/tests/home/search.spec.ts
  frontend/e2e/tests/home/sort.spec.ts
  frontend/e2e/types/filterTypes.ts
  frontend/e2e/utils/filter.ts
  frontend/e2e/utils/plugin.ts
  frontend/e2e/utils/search.ts
  frontend/package.json
Labels: cicd, testco-e2e

#965 Adding data-workflows unit tests to checks
  .github/workflows/dataworkflow-tests.yml
Labels: maintenance

#988 Installing test requirements for data-workflows test
  .github/workflows/dataworkflow-tests.yml
Labels: cicd

#991 Making dataworkflows timestamp window utc to be consistent
  data-workflows/activity/snowflake_adapter.py
  data-workflows/activity/tests/test_snowflake_adapter.py
Labels: bug-fix

#939 Create maintenance activity ETL workflow
  .happy/terraform/modules/ecs-stack/main.tf
  data-workflows/activity/github_activity_model.py
  data-workflows/activity/install_activity_model.py
  data-workflows/activity/processor.py
  data-workflows/activity/snowflake_adapter.py
  data-workflows/activity/tests/test_snowflake_adapter.py
  data-workflows/handler.py
  data-workflows/plugin/__init__.py
  data-workflows/plugin/helpers.py
  data-workflows/tests/test_handler.py
  data-workflows/utils/utils.py
Labels: new-feature
