Repository chanzuckerberg/napari-hub, pull requests merged in 2023-08, with the labels that each got.

#1184 Recomputing plugin with plugin_blocked trigger
  .happy/terraform/modules/ecs-stack/main.tf
  data-workflows/handler.py
  data-workflows/plugin/aggregator.py
  data-workflows/plugin/tests/test_aggregator.py
  data-workflows/plugin/tests/test_processor.py
  data-workflows/tests/test_handler.py
  data-workflows/tests/test_run_workflow.py
  napari-hub-commons/src/nhcommons/models/plugin.py
  napari-hub-commons/src/nhcommons/models/plugin_metadata.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin.py
  napari-hub-commons/src/nhcommons/utils/pypi_adapter.py
Labels: new-feature

#1194 Adding exception logging for Internal Server Error
  backend/api/app.py
  backend/api/metrics.py
Labels: maintenance

#1195 Migrating Zulip bot from backed to data-workflows
  .happy/terraform/modules/ecs-stack/main.tf
  backend/api/_tests/test_zulip.py
  backend/api/model.py
  backend/api/zulip.py
  data-workflows/plugin/processor.py
  data-workflows/plugin/tests/test_processor.py
  data-workflows/utils/tests/test_zulip.py
  data-workflows/utils/zulip.py
  napari-hub-commons/src/nhcommons/utils/request_adapter.py
Labels: maintenance

#1204 Removing backend workflow for writing plugin data to s3
  backend/api/app.py
  backend/api/model.py
  backend/api/s3.py
  backend/requirements.txt
  backend/utils/_tests/test_github.py
  backend/utils/_tests/test_pypi.py
  backend/utils/datadog.py
  backend/utils/pypi.py
  backend/utils/test_utils.py
  backend/utils/utils.py
Labels: maintenance

#1205 Removing backend plugin update metrics and alarms
  .happy/terraform/modules/cloudwatch-alarm/main.tf
Labels: maintenance

#1211 Removing deprecated endpoints from swagger
  backend/api/app.py
  backend/api/templates/swagger.yml
Labels: maintenance

#1207 Adding /plugins/index/all endpoint
  backend/api/_tests/test_home.py
  backend/api/_tests/test_model.py
  backend/api/app.py
  backend/api/home.py
  backend/api/model.py
  backend/api/models/_tests/test_plugin.py
  backend/api/models/plugin.py
  backend/bdd_tests/scenarios/plugin.feature
  backend/bdd_tests/test_homepage_plugin.py
  backend/bdd_tests/test_plugin.py
Labels: new-feature

#1221 Check for existence of github repo's `createdAt` field before displaying github commits data
  frontend/src/components/ActivityDashboard/ActivityMaintenanceSection/ActivityMaintenanceSection.tsx
Labels: bug-fix

#1226 Return 404 for plugins that don't exist
  backend/api/app.py
Labels: bug-fix

#1223 Show message for empty stats when timestamp is null
  frontend/src/components/ActivityDashboard/ActivityMaintenanceSection/ActivityMaintenanceSection.tsx
Labels: bug-fix

#1227 Update FAQ's instructions for hiding a plugin
  frontend/i18n/en/faq.mdx
Labels: maintenance

#1228 Update message displayed when we have no commit data for a plugin
  frontend/i18n/en/activity.json
Labels: bug-fix

#1212 Removing deprecated endpoints
  .happy/terraform/modules/ecs-stack/main.tf
  backend/api/app.py
  backend/api/model.py
  backend/api/models/_tests/test_plugin.py
  backend/api/models/_tests/test_plugin_blocked.py
  backend/api/models/plugin.py
  backend/api/models/plugin_blocked.py
  backend/bdd_tests/README.md
  backend/bdd_tests/conftest.py
  backend/bdd_tests/scenarios/category.feature
  backend/bdd_tests/scenarios/homepage_plugins.feature
  backend/bdd_tests/scenarios/metric.feature
  backend/bdd_tests/scenarios/plugin.feature
  backend/bdd_tests/test_category.py
  backend/bdd_tests/test_homepage_plugin.py
  backend/bdd_tests/test_metric.py
  backend/bdd_tests/test_plugin.py
  backend/bdd_tests/test_utils.py
Labels: maintenance

#1233 Adding data loading for local dynamo to bash script
  local-dynamo-setup.sh
Labels: new-feature
