Repository chanzuckerberg/napari-hub, pull requests merged in 2023-01, with the labels that each got.

#797 Updating cron frequency by environment
  .happy/terraform/modules/ecs-stack/main.tf
Labels: improvement

#822 Adjusting plugin_update_schedule expression for staging
  .happy/terraform/modules/ecs-stack/main.tf
Labels: bug-fix

#745 Filter layer quantifiers and add test
  backend/utils/_tests/test_utils.py
  backend/utils/utils.py
Labels: improvement

#839 Updating preview unit test
  backend/preview/_tests/test_preview_meta.py
Labels: maintenance

#840 Staging front end ECS task count to default to 1
  .happy/terraform/envs/staging/main.tf
Labels: maintenance
