Repository chanzuckerberg/napari-hub, pull requests merged in 2023-07, with the labels that each got.

#1112 Returning empty list on no collection
  backend/api/plugin_collections.py
  backend/utils/github.py
Labels: bug-fix

#1115 Adding Plugins API to use dynamo
  .happy/terraform/modules/ecs-stack/main.tf
  backend/api/_tests/test_shield.py
  backend/api/app.py
  backend/api/model.py
  backend/api/models/_tests/conftest.py
  backend/api/models/_tests/test_category.py
  backend/api/models/_tests/test_github_activity.py
  backend/api/models/_tests/test_install_activity.py
  backend/api/models/install_activity.py
  backend/api/models/plugin.py
  backend/api/models/plugin_blocked.py
  backend/api/models/plugin_metadata.py
  backend/api/shield.py
  backend/bdd_tests/scenarios/plugin.feature
  backend/bdd_tests/test_plugin.py
  backend/bdd_tests/test_utils.py
Labels: new-feature

#1120 Adding tests workflow for nhcommons
  .github/workflows/nh-commons-tests.yml
  napari-hub-commons/src/nhcommons/utils/pypi_adapter.py
Labels: new-feature

#1132 Adding plugins api for homepage
  backend/api/app.py
  backend/api/home.py
  backend/bdd_tests/scenarios/homepage_plugins.feature
  backend/bdd_tests/test_homepage_plugin.py
  backend/bdd_tests/test_utils.py
Labels: new-feature

#1136 Adding unit tests for plugins api for homepage
  backend/api/_tests/test_home.py
  backend/api/home.py
Labels: maintenance

#1144 Add enforce release label workflow
  .github/check-labels.js
  .github/workflows/enforce-labels.yml
Labels: cicd

#1150 Improve Enforce Release Label Workflow
  .github/check-labels.js
Labels: cicd

#1148 data-workflows maintenance data fetch cleanup
  .happy/terraform/modules/ecs-stack/main.tf
  data-workflows/activity/github_activity_model.py
  data-workflows/activity/install_activity_model.py
  data-workflows/activity/processor.py
  data-workflows/activity/tests/test_github_activity_model.py
  data-workflows/activity/tests/test_install_activity_model.py
  data-workflows/activity/tests/test_processor.py
  data-workflows/plugin/helpers.py
  napari-hub-commons/src/nhcommons/models/plugin.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin.py
  napari-hub-commons/src/nhcommons/utils/adapter_helpers.py
Labels: improvement

#1126 Plugin optimization and cleanup
  .happy/terraform/modules/cloudwatch-alarm/main.tf
  .happy/terraform/modules/ecs-stack/main.tf
  backend/api/model.py
  backend/api/models/_tests/test_plugin.py
  backend/api/models/_tests/test_plugin_blocked.py
  backend/api/models/_tests/test_plugin_metadata.py
  backend/api/models/plugin.py
  backend/api/models/plugin_blocked.py
  backend/api/models/plugin_metadata.py
  data-workflows/plugin/aggregator.py
  data-workflows/plugin/processor.py
Labels: maintenance

#1165 PR release comment workflow
  .github/pr-release-comment.js
  .github/workflows/pr-release-comment.yml
Labels: cicd

#1170 Increasing authenticated role-duration-seconds for deploy
  .github/workflows/deploy.yml
  .github/workflows/push-rdev.yml
Labels: cicd

#1098 Move data-workflows dynamo models to napari-hub-commons
  data-workflows/activity/github_activity_model.py
  data-workflows/activity/install_activity_model.py
  data-workflows/activity/tests/test_github_activity_model.py
  data-workflows/activity/tests/test_install_activity_model.py
  data-workflows/categories/processor.py
  data-workflows/categories/tests/test_processor.py
  data-workflows/conftest.py
  data-workflows/requirements.txt
  frontend/src/store/search/filter.store.ts
  napari-hub-commons/setup.py
  napari-hub-commons/src/nhcommons/__init__.py
  napari-hub-commons/src/nhcommons/models/__init__.py
  napari-hub-commons/src/nhcommons/models/category.py
  napari-hub-commons/src/nhcommons/models/github_activity.py
  napari-hub-commons/src/nhcommons/models/helper.py
  napari-hub-commons/src/nhcommons/models/install_activity.py
  napari-hub-commons/src/nhcommons/models/plugin.py
  napari-hub-commons/src/nhcommons/models/plugin_metadata.py
  napari-hub-commons/src/nhcommons/models/plugins_blocked.py
  napari-hub-commons/src/nhcommons/tests/models/conftest.py
  napari-hub-commons/src/nhcommons/tests/models/test_category.py
  napari-hub-commons/src/nhcommons/tests/models/test_github_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_install_activity.py
  napari-hub-commons/src/nhcommons/tests/models/test_plugin.py
  napari-hub-commons/src/nhcommons/tests/utils/test_time.py
Labels: maintenance

#1172 Adding s3 read permission to data workflow for categories
  .happy/terraform/modules/ecs-stack/main.tf
Labels: bug-fix

#1175 Improve Release Workflow
  .github/workflows/deploy.yml
  .github/workflows/pr-release-comment.yml
  .github/workflows/release.yml
Labels: cicd

#1181 Metrics feature flag clean up
  .happy/terraform/modules/cloudwatch-alarm/main.tf
  .happy/terraform/modules/ecs-stack/main.tf
  backend/api/_tests/test_activity_dashboard.py
  backend/api/_tests/test_fixtures.py
  backend/api/_tests/test_metrics.py
  backend/api/app.py
  backend/api/metrics.py
  backend/api/model.py
  backend/api/models/_tests/conftest.py
  backend/api/models/_tests/test_github_activity.py
  backend/api/models/_tests/test_install_activity.py
  backend/api/models/github_activity.py
  backend/api/s3.py
  backend/requirements.txt
Labels: maintenance, clean-up

#1183 Enable streaming for plugins_blocked
  .happy/terraform/modules/ecs-stack/main.tf
Labels: new-feature
